export const MSG = {
  // Client -> Server (Room lifecycle)
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  LIST_ROOMS: 'LIST_ROOMS',
  DELETE_ROOM: 'DELETE_ROOM',
  REMOVE_ROOM: 'REMOVE_ROOM',

  // Client -> Server (Room interaction)
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  SPECTATE: 'SPECTATE',
  LEAVE_SPECTATE: 'LEAVE_SPECTATE',
  JOIN_ROOM_FROM_SPECTATE: 'JOIN_ROOM_FROM_SPECTATE',

  // Client -> Server (Identity)
  IDENTIFY: 'IDENTIFY',
  CONSOLIDATE: 'CONSOLIDATE',
  UPDATE_SECRET_CODE: 'UPDATE_SECRET_CODE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  GET_USER_INFO: 'GET_USER_INFO',
  BUG_REPORT: 'BUG_REPORT',
  PAIR_BUG_REPORT: 'PAIR_BUG_REPORT',

  // Server -> Client (Room)
  ROOM_LIST: 'ROOM_LIST',
  ROOM_JOINED: 'ROOM_JOINED',
  ROOM_LEFT: 'ROOM_LEFT',
  ROOM_DELETED: 'ROOM_DELETED',
  MEMBER_JOINED: 'MEMBER_JOINED',
  MEMBER_LEFT: 'MEMBER_LEFT',
  MEMBER_DISCONNECTED: 'MEMBER_DISCONNECTED',
  HOST_CHANGED: 'HOST_CHANGED',
  CHAT_HISTORY: 'CHAT_HISTORY',

  // Server -> Client (Spectator)
  SPECTATE_JOINED: 'SPECTATE_JOINED',
  SPECTATE_LEFT: 'SPECTATE_LEFT',
  SPECTATOR_JOINED: 'SPECTATOR_JOINED',
  SPECTATOR_LEFT: 'SPECTATOR_LEFT',

  // Server -> Client (Identity)
  SERVER_CONFIG: 'SERVER_CONFIG',
  ERROR: 'ERROR',
  PROFILE: 'PROFILE',
  TOKEN_REDIRECT: 'TOKEN_REDIRECT',
  CONSOLIDATE_OK: 'CONSOLIDATE_OK',
  CONSOLIDATE_FAILED: 'CONSOLIDATE_FAILED',
  SECRET_CODE_OK: 'SECRET_CODE_OK',
  SECRET_CODE_FAILED: 'SECRET_CODE_FAILED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  USER_INFO: 'USER_INFO',
  BUG_REPORT_OK: 'BUG_REPORT_OK',
  PAIR_OK: 'PAIR_OK',
} as const;

export type MessageType = typeof MSG[keyof typeof MSG];
