// [impl:uuid:e7209648-2e3e-49d0-a8a2-f6353d7735b5] T5 message types
export const MSG = {
  // Client -> Server (Room lifecycle)
  CREATE_ROOM: 'CREATE_ROOM',
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  LIST_ROOMS: 'LIST_ROOMS',
  DELETE_ROOM: 'DELETE_ROOM', UPDATE_ROOM_CONFIG: 'UPDATE_ROOM_CONFIG', ROOM_CONFIG_UPDATED: 'ROOM_CONFIG_UPDATED',
  REMOVE_ROOM: 'REMOVE_ROOM',
  ROOM_APPLY: 'ROOM_APPLY', ROOM_APPLY_RECEIVED: 'ROOM_APPLY_RECEIVED', ROOM_APPLY_ACCEPT: 'ROOM_APPLY_ACCEPT', ROOM_APPLY_ACCEPTED: 'ROOM_APPLY_ACCEPTED',
  MEMBER_RECONNECTED: 'MEMBER_RECONNECTED',

  // Client -> Server (Room interaction)
  CHAT_MESSAGE: 'CHAT_MESSAGE',

  // Client -> Server (Identity)
  IDENTIFY: 'IDENTIFY',
  CONSOLIDATE: 'CONSOLIDATE',
  UPDATE_SECRET_CODE: 'UPDATE_SECRET_CODE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  GET_USER_INFO: 'GET_USER_INFO',
  DEVICE_ENROLL_REQUEST: 'DEVICE_ENROLL_REQUEST',
  DEVICE_AUTH: 'DEVICE_AUTH',
  BUG_REPORT: 'BUG_REPORT',
  PAIR_BUG_REPORT: 'PAIR_BUG_REPORT',

  // Server -> Client (Room)
  ROOM_LIST: 'ROOM_LIST',
  ROOM_JOINED: 'ROOM_JOINED',
  ROOM_LEFT: 'ROOM_LEFT',
  ROOM_DELETED: 'ROOM_DELETED',
  MEMBER_JOINED: 'MEMBER_JOINED',
  MEMBER_LEFT: 'MEMBER_LEFT',
  MEMBER_DISCONNECTED: 'MEMBER_DISCONNECTED',
  HOST_CHANGED: 'HOST_CHANGED',
  CHAT_HISTORY: 'CHAT_HISTORY',

  // Server -> Client (Identity)
  SERVER_CONFIG: 'SERVER_CONFIG',
  ERROR: 'ERROR',
  PROFILE: 'PROFILE',
  TOKEN_REDIRECT: 'TOKEN_REDIRECT',
  CONSOLIDATE_OK: 'CONSOLIDATE_OK',
  CONSOLIDATE_FAILED: 'CONSOLIDATE_FAILED',
  SECRET_CODE_OK: 'SECRET_CODE_OK',
  SECRET_CODE_FAILED: 'SECRET_CODE_FAILED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  USER_INFO: 'USER_INFO',
  DEVICE_ENROLL_OK: 'DEVICE_ENROLL_OK',
  DEVICE_ENROLL_FAILED: 'DEVICE_ENROLL_FAILED',
  DEVICE_AUTH_OK: 'DEVICE_AUTH_OK',
  DEVICE_AUTH_FAILED: 'DEVICE_AUTH_FAILED',
  BUG_REPORT_OK: 'BUG_REPORT_OK',
  PAIR_OK: 'PAIR_OK',
} as const;

export type MessageType = typeof MSG[keyof typeof MSG];
