/**
 * T102 — Traceability matrix consistency + fix engine.
 *
 * Scans the scrum.pmo sprint tree, builds a T101 TraceGraph (Requirement↔Task) plus per-task
 * chain-coverage flags (req/uc/puml/method/uuid), validates the chain, and regenerates a
 * marker-delimited region of scrum.pmo/traceability-matrix.md WITHOUT touching manual content
 * outside the markers. Idempotent; report-only `check` exits non-zero on drift (CI-usable).
 *
 * [impl:uuid:102b1c2d-3e4f-4051-9728-b02020202102] R15.1 matrix consistency + fix
 */
import fs from 'node:fs';
import path from 'node:path';
import { TraceGraph, Requirement, Task, isUuidV4 } from '../shared/TraceModel.js';

export const REGION_BEGIN = '<!-- TRACE:BEGIN (generated by TraceConsistency — do not edit inside) -->';
export const REGION_END = '<!-- TRACE:END -->';

export interface TaskCoverage {
  sprint: string;
  task: string;          // task file slug (no .md)
  uuid: string | null;   // task:uuid if present
  reqUuid: string | null;// up-linked requirement:uuid if present
  req: boolean; uc: boolean; puml: boolean; method: boolean;
}

export interface Issue {
  level: 'error' | 'warn';
  ref: string;           // route-like ref or file location
  reason: string;
}

const RE = {
  reqUuid: /\[requirement:uuid:([0-9a-f-]{36})\]/i,
  taskUuid: /\[task:uuid:([0-9a-f-]{36})\]/i,
  fwdTask: /→\s*\[T?\d+[^\]]*\]\(\.\/(task-[^)]+?)\.md\)/gi,
  uc: /\b(UC-[A-Z]|uc:uuid:)/,
  puml: /\.puml\b|\/diagrams\/|\[class:uuid:|\[uc:uuid:/,
  method: /\bsrc\/|\.ts:|\.ts`|[A-Z][a-zA-Z]+\.[a-z][a-zA-Z]+\(/,
};

/** Scan the sprint tree → typed graph (Requirement↔Task) + per-task coverage. */
export function scanRepo(sprintsDir: string): { graph: TraceGraph; coverage: TaskCoverage[] } {
  const graph = new TraceGraph();
  const coverage: TaskCoverage[] = [];
  if (!fs.existsSync(sprintsDir)) return { graph, coverage };

  // Pass 1: requirements — create Requirement objects, remember forward task slugs.
  const reqForwardTasks = new Map<string, Set<string>>(); // requirement uuid -> task slugs
  for (const sprint of fs.readdirSync(sprintsDir)) {
    const reqPath = path.join(sprintsDir, sprint, 'requirements.md');
    if (!fs.existsSync(reqPath)) continue;
    const text = fs.readFileSync(reqPath, 'utf-8');
    // split into requirement blocks by the requirement:uuid tag
    const blocks = text.split(/(?=\[requirement:uuid:)/i);
    for (const block of blocks) {
      const m = block.match(RE.reqUuid);
      if (!m || !isUuidV4(m[1])) continue;
      const uuid = m[1].toLowerCase();
      if (!graph.has(uuid)) new Requirement(graph, uuid, firstLine(block));
      const slugs = reqForwardTasks.get(uuid) ?? new Set<string>();
      for (const fm of block.matchAll(RE.fwdTask)) slugs.add(fm[1]);
      reqForwardTasks.set(uuid, slugs);
    }
  }

  // Pass 2: tasks — create Task objects + coverage, link up to requirements.
  const taskBySlug = new Map<string, Task>();
  for (const sprint of fs.readdirSync(sprintsDir)) {
    const dir = path.join(sprintsDir, sprint);
    if (!fs.statSync(dir).isDirectory()) continue;
    for (const file of fs.readdirSync(dir)) {
      if (!/^task-.*\.md$/.test(file)) continue;
      const slug = file.replace(/\.md$/, '');
      const text = fs.readFileSync(path.join(dir, file), 'utf-8');
      const tm = text.match(RE.taskUuid);
      const uuid = tm && isUuidV4(tm[1]) ? tm[1].toLowerCase() : null;
      const rm = text.match(RE.reqUuid);
      const reqUuid = rm && isUuidV4(rm[1]) ? rm[1].toLowerCase() : null;
      const cov: TaskCoverage = {
        sprint, task: slug, uuid, reqUuid,
        req: !!reqUuid, uc: RE.uc.test(text), puml: RE.puml.test(text), method: RE.method.test(text),
      };
      coverage.push(cov);
      if (uuid && !graph.has(uuid)) {
        const t = new Task(graph, uuid, slug);
        taskBySlug.set(slug, t);
        if (reqUuid && graph.get(reqUuid)) (graph.get(reqUuid) as Requirement).addTask(t);
      }
    }
  }

  // Pass 3: requirement forward links by slug (req → task even if task up-link absent).
  for (const [reqUuid, slugs] of reqForwardTasks) {
    const req = graph.get(reqUuid) as Requirement | undefined;
    if (!req) continue;
    for (const slug of slugs) {
      const t = taskBySlug.get(slug);
      if (t) req.addTask(t);
    }
  }

  coverage.sort((a, b) => a.sprint.localeCompare(b.sprint, undefined, { numeric: true }) || a.task.localeCompare(b.task, undefined, { numeric: true }));
  return { graph, coverage };
}

function firstLine(block: string): string {
  const line = block.split('\n').map(s => s.trim()).find(s => s && !s.startsWith('[requirement'));
  return (line || 'requirement').replace(/^[-*]\s*\[.\]\s*/, '').slice(0, 120);
}

/** Validate the chain. Returns issues (errors break consistency; warns are gaps). */
export function validate(graph: TraceGraph, coverage: TaskCoverage[]): Issue[] {
  const issues: Issue[] = [];
  for (const c of coverage) {
    if (!c.uuid) issues.push({ level: 'error', ref: `${c.sprint}/${c.task}`, reason: 'task has no [task:uuid] tag' });
    if (c.reqUuid && !graph.has(c.reqUuid)) {
      issues.push({ level: 'error', ref: `task:${c.uuid ?? c.task}`, reason: `up-link requirement:uuid ${c.reqUuid} not found in any requirements.md` });
    }
    if (!c.req) issues.push({ level: 'warn', ref: `${c.sprint}/${c.task}`, reason: 'no requirement up-link (chain start missing)' });
  }
  // requirements with no forward task = dangling requirement
  for (const req of graph.ofType('requirement') as Requirement[]) {
    if (req.tasks.length === 0) {
      issues.push({ level: 'error', ref: `requirement:${req.uuid}`, reason: 'requirement has no linked task (no forward link / no task up-link)' });
    }
  }
  return issues;
}

export function formatReport(issues: Issue[]): string {
  if (issues.length === 0) return 'Traceability matrix CONSISTENT — 0 issues.';
  const errors = issues.filter(i => i.level === 'error');
  const warns = issues.filter(i => i.level === 'warn');
  const lines = [`Traceability issues: ${errors.length} error(s), ${warns.length} warning(s)`];
  for (const i of issues) lines.push(`  [${i.level.toUpperCase()}] ${i.ref} — ${i.reason}`);
  return lines.join('\n');
}

/** The generated coverage table (deterministic — same graph → same text → idempotent). */
export function generateRegion(coverage: TaskCoverage[]): string {
  const cell = (b: boolean) => (b ? '✓' : '✗');
  const rows = coverage.map(c =>
    `| ${c.sprint} | ${c.task} | ${cell(c.req)} | ${cell(c.uc)} | ${cell(c.puml)} | ${cell(c.method)} | ${cell(!!c.uuid)} |`
  );
  return [
    REGION_BEGIN,
    '',
    '| Sprint | Task | req | uc | puml | method | uuid |',
    '|--------|------|:--:|:--:|:--:|:--:|:--:|',
    ...rows,
    '',
    REGION_END,
  ].join('\n');
}

/**
 * Write the generated region into matrixPath between the markers. Manual content outside the
 * markers is preserved verbatim. If no markers exist, the region is appended (manual table left
 * untouched). Idempotent: returns { changed:false } when the file already matches.
 */
export function fixMatrix(matrixPath: string, coverage: TaskCoverage[]): { changed: boolean } {
  const region = generateRegion(coverage);
  const existing = fs.existsSync(matrixPath) ? fs.readFileSync(matrixPath, 'utf-8') : '';
  let next: string;
  const b = existing.indexOf(REGION_BEGIN);
  const e = existing.indexOf(REGION_END);
  if (b !== -1 && e !== -1 && e > b) {
    next = existing.slice(0, b) + region + existing.slice(e + REGION_END.length);
  } else {
    next = (existing.trimEnd() + '\n\n' + region + '\n').replace(/^\n+/, '');
  }
  if (next === existing) return { changed: false };
  fs.writeFileSync(matrixPath, next);
  return { changed: true };
}
